#!/usr/bin/env bash

origin=$1
_basename=$(basename $origin)
folder=${_basename%.*}
echo "$folder"

if [ -d "$folder" ]; then
	echo "$folder exists"
	exit 1
fi

mkdir "$folder"
cd "$folder" || exit 2

# reate empty git repo
git init
git remote add origin "$origin"

# enable partial clone and sparse checkout
git sparse-checkout init --cone
git config remote.origin.promisor true
git config remote.origin.partialCloneFilter blob:none

branch=master
if [ -z "$(git ls-remote --heads origin master)" ]; then
	branch=main
fi

echo 'start fetching...'
git fetch --depth 1 origin $branch
git checkout --track origin/$branch
git maintenance start
